services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.com/images:/app/images
    # This is for testing purposes.
    # TODO: Remove before deploying. -- START
    # ports:
    #   - 3000:3000
    # TODO: Remove before deploying. -- END
    depends_on:
      - db

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/data/lenslocked.com/caddy:/data

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/lenslocked.com/psql:/var/lib/postgresql/data/pgdata
